config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :foods, only: %i[index create destroy]
  resources :recipes, only: %i[index new create show destroy]
  resources :public_recipes, only: %i[index]
  get 'general_shopping_list', to: 'users#index', as: 'shopping_list'
  resources :recipe_foods, only: %i[index new edit update destroy create]

  # Defines the root path route ("/")
  root "public_recipes#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id', inverse_of: :recipes
  has_many :recipe_foods, class_name: 'RecipeFood', foreign_key: 'recipe_id', inverse_of: :recipe, dependent: :destroy

  validates :name, presence: true, length: { maximum: 300 }
  validates :preparation_time, numericality: true, comparison: { greater_than: 0 }
  validates :cooking_time, numericality: true, comparison: { greater_than: 0 }
  validates :description, presence: true

  after_initialize :default_values

  scope :others_public_recipes, -> { where('user != @current_user and public == true') }

  def total_ingredients
    foods.length
  end

  private

  def default_values
    self.public ||= false
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @current_user = current_user
    @recipes = @current_user.recipes.order(created_at: :desc)
  end

  def show
    @current_user = current_user
    @recipe = Recipe.find(params[:id])
    @f_field = params[:field] || 'name'
    @f_order = params[:order] || 'asc'
    @rec_foods = RecipeFood.joins(:food).where(recipe_id: params[:id]).order("#{@f_field} #{@f_order}").includes(:food)
  end

  def new
    @current_user = current_user
  end

  def create
    @current_user = current_user
    @recipe = @current_user.recipes.new(recipe_params)
    if @recipe.save
      flash[:notice] = 'Recipe created successfully'
      redirect_to recipes_url
    else
      flash.now[:alert] = @recipe.errors.full_messages.to_sentence
      render :new, status: 422
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe][:recipe_id])
    if @recipe.destroy
      flash[:notice] = "Recipe's food removed!"
    else
      flash[:alert] = "Recipe's food couldn't be removed, please try again."
    end
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/views/recipes/_add_ingredient_form.html.erb
<%= form_with(model: food, url: recipe_foods_url, scope: :ingredient, class: 'text-black') do |f| %>
  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Add ingredient</h5>
  </div>
  <div class="modal-body">
    <% if food.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(food.errors.count, 'error') %> prohibited this ingredients from being saved:</h2>

        <ul>
          <% food.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :ingredient %><br />
      <%= f.search_field :ingredient, autofocus: true, autocomplete: "ingredient", list: 'foods' %>
      <datalist id="foods">
        <% Food.all.each do |food| %>
          <option value="<%= food.name %>">
        <% end %>
      <datalist>
    </div>

    <div class="form-group">
      <%= f.label :quantity %><br />
      <%= f.number_field :quantity, autofocus: true, autocomplete: "quantity" %>
    </div>

    <div class="form-group">
      <%= f.hidden_field :recipe, value: recipe_id %>
    </div>
  </div>

  <div class="modal-footer justify-content-start">
    <% if food.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', food, method: :delete, class: 'text_danger', data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <%= f.submit class: 'btn btn-primary float-left' %>
  </div>
<% end %>

app/views/recipes/_recipe_card.html.erb
<div class="card__box">
  <div class="card__box-head">
    <%= tag.h2(recipe.name, class: 'card__title') %>
    <% if can? :destroy, recipe %>
      <%= button_to 'Remove', recipe_path(recipe.id), params: { recipe: { recipe_id: recipe.id} }, method: :delete, class: 'link remove__link-float', id: "btn__delete-recipe-#{recipe.id}" %>
      <% end %>
  </div>
  <div class="card__box-description">
    <%= tag.p(recipe.description, class: ['card__text', ('truncated-text' unless detailed)]) %>
  </div>
  <%= link_to '', recipe_path(recipe.id), id: "link_recipe-#{recipe.id}", class: 'card__hidden-link' %>
</div>

app/views/recipes/index.html.erb
<div class="section__submenu">
  <%= link_to 'New Recipe', new_recipe_path, class: 'btn btn-primary w-20' %>
</div>
<div class="section__list">
<%= render partial: 'recipe_card', collection: @recipes, as: :recipe, locals: { detailed: false } %>
</div>

app/views/recipes/new.html.erb
<div class="form__container">
<%= tag.h1('New Recipe', class: 'form__title') %>
<%= form_with model: Recipe.new do |f| %>
  <%= f.text_field :name, placeholder: 'Name' %>
  <%= f.text_field :preparation_time, placeholder: 'Preparation time (hours)' %>
  <%= f.text_field :cooking_time, placeholder: 'Cooking time (hours)' %>
  <%= f.text_area :description, rows: 15, placeholder: 'Enter the description' %>
  <div class="field">
    <%= f.label :public %>
    <%= f.check_box :public, {checked: true}, true, false %>
  </div>
  <%= f.submit 'Save', class: 'btnn' %>
<% end %>
</div>

app/views/recipes/show.html.erb
<div class="recipe__details">
<%= tag.h1(@recipe.name) %>
<div class="recipe__info">
  <div class="recipe__info-item">
    <%= tag.span('Preparation time:') %>
    <%= tag.p("#{@recipe.preparation_time} hours") %>
  </div>
  <div class="recipe__info-item">
    <%= tag.span('Cooking time:') %>
    <%= tag.p("#{@recipe.cooking_time} hours") %>
  </div>
  <div class="recipe__info-item">
    <%= @recipe.description %>
  </div>
  <div class="recipe__info-item public__item-float">
    <%= tag.span('Public:') %>
    <label class="toggle__switch">
      <%= check_box_tag 'public_recipe', 'yes', @recipe.public, disabled: true %>
      <span class="slider round"></span>
    </label>
  </div>
</div>
<div class="recipe__buttons">
  <% if can? :destroy, @recipe %>
    <%= link_to 'Generate shopping list', shopping_list_path, class: 'btnn' %>
    <button type="button" class="btn btn-secondary text-white" data-bs-toggle="modal" data-bs-target="#newIngredientModal">
        Add ingredient
      </button>

      <div class="modal fade" id="newIngredientModal" tabindex="-1" aria-labelledby="newIngredientModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <%= render partial: 'recipes/add_ingredient_form', locals: { food: RecipeFood.new, recipe_id: params[:id] }%>
          </div>
        </div>
      </div>
  <% end %>
</div>
<div class="recipe__ingredients">
  <table>
    <thead>
    <tr>
      <th><%= link_to 'Food', recipe_path(@recipe.id, field: 'name', order: (@f_field == 'name' && @f_order == 'asc' ? 'desc' : 'asc')), class: 'link link__table-head' %></th>
      <th><%= link_to 'Quantity', recipe_path(@recipe.id, field: 'quantity', order: (@f_field == 'quantity' && @f_order == 'asc' ? 'desc' : 'asc')), class: 'link link__table-head' %></th>
      <th>Value</th>
      <% if can? :destroy, @recipe %>
      <th>Action</th>
      <% end %>
    </tr>
    </thead>
    <tbody>
      <% @rec_foods.each do |rf| %>
        <tr>
          <td><%= rf.food.name %></td>
          <td><%= rf.quantity %></td>
          <td><%= "$ #{rf.quantity * rf.food.price}" %></td>
          <% if can? :destroy, @recipe %>
          <td class="table__actions">
            <%= link_to 'Modify', edit_recipe_food_path(rf.id), class: 'link' %>
            <%= button_to 'Remove', recipe_food_path(rf.id), params: { recipe_food: { rf_id: rf.id }}, method: :delete, class: 'link' %>
          </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>