config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :foods, only: %i[index create destroy]
  resources :recipes, only: %i[index new create show destroy]
  resources :public_recipes, only: %i[index]
  get 'general_shopping_list', to: 'users#index', as: 'shopping_list'
  resources :recipe_foods, only: %i[index new edit update destroy create]

  # Defines the root path route ("/")
  root "public_recipes#index"
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id', inverse_of: :foods
  has_many :recipe_foods, class_name: 'RecipeFood', foreign_key: 'food_id', inverse_of: :food, dependent: :destroy
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @items = current_user.foods.order(created_at: :desc)
  end

  def create
    food = Food.new(foods_params)
    p food
    food.user = current_user

    if food.save
      flash[:success] = 'Food item has been created'
    else
      flash[:alert] = 'Food item could not be saved'
    end
    redirect_to foods_path
  end

  # /foods/:id (delete)
  def destroy
    if Food.find(params[:id]).destroy
      flash[:success] = 'Food item has been deleted'
    else
      flash[:alert] = 'Food item could not be deleted'
    end
    redirect_to foods_path
  end

  # public: gets the most recent posts from the database
  #
  # returns an array of at most 15 posts
  def most_recent_added
    Food.order(id: :desc).limit(15)
  end

  private

  def foods_params
    par = params[:foods].permit(:name, :measurement_unit, :price)
    par[:price] = par[:price].to_f
    par
  end
end

app/views/foods/_form.html.erb
<%= form_with(model: food, url: foods_url, scope: :foods, class: 'text-black' ) do |f| %>
 <button type="button" class="btn btn-primary w-25" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Add Food
</button>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create food</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
    <% if food.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(food.errors.count, 'error') %> prohibited this ingredients from being saved:</h2>

        <ul>
          <% food.erros.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
    </div>

    <div class="form-group">
      <%= f.label :measurement_unit %><br />
      <%= f.text_field :measurement_unit , autofocus: true, autocomplete: "measurement unit " %>
    </div>

    <div class="form-group">
      <%= f.label :price %><br />
      <%= f.text_field :price, autofocus: true, autocomplete: "price" %>
        </div>
  </div>
      <div class="modal-footer">
        <% if food.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', food, method: :delete, class: 'text_danger', data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
    <%= f.submit class: 'btn btn-primary float-left' %>
      </div>
    </div>
  </div>
</div>
 
<% end %>

app/views/foods/index.html.erb
<section class="container-fluid d-flex flex-column gap-3">
  <%= render partial: 'foods/form', locals: { food: Food.new } %>
  <div class="foods-table">
    <%= render partial: 'layouts/table' %>
  </div>
</section>