config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :foods, only: %i[index create destroy]
  resources :recipes, only: %i[index new create show destroy]
  resources :public_recipes, only: %i[index]
  get 'general_shopping_list', to: 'users#index', as: 'shopping_list'
  resources :recipe_foods, only: %i[index new edit update destroy create]

  # Defines the root path route ("/")
  root "public_recipes#index"
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light auto">
  <div class="container">
    <a class="navbar-brand brand" href="#">Recipe App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', foods_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'My Recipes', recipes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Public Recipes', public_recipes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Foods', foods_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log Out', destroy_user_session_path, 'data-turbo-method': :delete, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_table.html.erb
<table class="table shadow table-striped">
  <thead>
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Measurement unit</th>
      <th scope="col">Unit price</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody class="foods-table">
    <% @items.each do |item| %>
      <tr>
        <th scope="row"><%= item.name %></th>
        <td><%= item.measurement_unit %></td>
        <td><%= item.price %></td>
        <td><%= button_to 'Delete', food_path(item.id), class: 'btn btn-danger', method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeAppRailsGroupCapstone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <section class="main_section">
      <div class="container">
      <% if user_signed_in? %>
        <%= render partial: 'layouts/header' %>
      <% end %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>